USE DATABASE DE_2;
USE SCHEMA DW;

-- 05_model_dw.sql
CREATE OR REPLACE PROCEDURE DW.TRANSFORM_FCT_WEATHER()
RETURNS STRING
LANGUAGE SQL
AS
$$
-- Ensure DW table exists
CREATE TABLE IF NOT EXISTS DW.FCT_WEATHER (
    LOCATION_NAME STRING,
    HOUR TIMESTAMP_NTZ,
    AVG_TEMPERATURE FLOAT,
    TOTAL_PRECIPITATION FLOAT
);

-- Get latest load timestamp from STG
SET latest_load_ts = (
    SELECT MAX(LOAD_TS)
    FROM STG.WEATHER_HOURLY
);

-- Aggregate only the latest load
CREATE OR REPLACE TEMPORARY TABLE DW.FCT_WEATHER_TMP AS
SELECT
    LOCATION_NAME,
    DATE_TRUNC('hour', TIME) AS HOUR,
    AVG(TEMPERATURE) AS AVG_TEMPERATURE,
    SUM(PRECIPITATION) AS TOTAL_PRECIPITATION
FROM STG.WEATHER_HOURLY
WHERE LOAD_TS = $latest_load_ts
GROUP BY 1, 2;

-- Merge incremental results into the DW fact table
MERGE INTO DW.FCT_WEATHER t
USING DW.FCT_WEATHER_TMP s
ON t.LOCATION_NAME = s.LOCATION_NAME
   AND t.HOUR = s.HOUR
WHEN MATCHED THEN UPDATE SET
    t.AVG_TEMPERATURE = s.AVG_TEMPERATURE,
    t.TOTAL_PRECIPITATION = s.TOTAL_PRECIPITATION
WHEN NOT MATCHED THEN
    INSERT (LOCATION_NAME, HOUR, AVG_TEMPERATURE, TOTAL_PRECIPITATION)
    VALUES (s.LOCATION_NAME, s.HOUR, s.AVG_TEMPERATURE, s.TOTAL_PRECIPITATION);

-- Return confirmation message
SELECT ' DW fact table updated for LOAD_TS: ' || $latest_load_ts AS STATUS;
$$;
